#!/usr/bin/env bash
# Convert shared Claude agents, skills, and commands to project-local Codex files.
set -euo pipefail
# TOML escaping examines individual bytes. macOS awk can split a UTF-8
# character in substr() and then reject that byte in a locale-aware regex.
# C locale preserves the original UTF-8 bytes while matching ASCII syntax.
export LC_ALL=C
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_DIR="$SCRIPT_DIR"
TARGET_DIR="$(dirname "$SCRIPT_DIR")"
DRY_RUN=false
GIT_EXCLUDE=false
help() {
  cat <<'EOF'
Usage: claude-to-codex.sh [--source DIR] [--target DIR] [--dry-run] [--git-exclude]

Defaults: source is this script's directory; target is its parent workspace.
Agents -> .codex/agents/*.toml; skills and commands -> .agents/skills/*.
Only converter-owned output and legacy sync-generated files are replaced.
Handwritten files/directories are preserved. All inputs are validated first.

Optional environment mappings (unset means inherit the parent session model):
  CODEX_MODEL_OPUS, CODEX_MODEL_SONNET, CODEX_MODEL_HAIKU
  CODEX_REASONING_EFFORT (applies only to explicitly mapped models)
Use exact model IDs and reasoning levels supported by your Codex account.
EOF
}
while [ "$#" -gt 0 ]; do
  case "$1" in
    --source|--target)
      [ "$#" -ge 2 ] || { help >&2; exit 1; }
      if [ "$1" = --source ]; then SOURCE_DIR="$2"; else TARGET_DIR="$2"; fi
      shift 2 ;;
    --dry-run) DRY_RUN=true; shift ;;
    --git-exclude) GIT_EXCLUDE=true; shift ;;
    -h|--help) help; exit 0 ;;
    *) echo "Unknown option: $1" >&2; help >&2; exit 1 ;;
  esac
done
[ -d "$SOURCE_DIR" ] || { echo "Missing source directory: $SOURCE_DIR" >&2; exit 1; }
SOURCE_DIR="$(cd "$SOURCE_DIR" && pwd)"
case "$TARGET_DIR" in /*) ;; *) TARGET_DIR="$PWD/$TARGET_DIR" ;; esac
case "${CODEX_REASONING_EFFORT:-}" in
  ''|low|medium|high|xhigh|max|ultra) ;;
  *) echo 'Invalid CODEX_REASONING_EFFORT' >&2; exit 1 ;;
esac
stage=$(mktemp -d)
trap 'rm -rf "$stage"' EXIT
mkdir -p "$stage/agents" "$stage/skills"

# Stage all conversions before modifying the destination.
for src in "$SOURCE_DIR"/agents/*.md; do
  [ -f "$src" ] || continue
  filename="$(basename "$src" .md)"
  filename="${filename%.agent}"
  [ ! -e "$stage/agents/$filename.toml" ] || { echo "Agent filename collision: $filename" >&2; exit 1; }
  awk -v mode=agent -f "$SCRIPT_DIR/claude-to-codex.awk" "$src" > "$stage/agents/$filename.toml"
done
for src in "$SOURCE_DIR"/skills/*/SKILL.md; do
  [ -f "$src" ] || continue
  name="$(basename "$(dirname "$src")")"
  cp -RL "$(dirname "$src")" "$stage/skills/$name"
  rm -f "$stage/skills/$name/SKILL.md"
  awk -v mode=skill -f "$SCRIPT_DIR/claude-to-codex.awk" "$src" > "$stage/skills/$name/SKILL.md"
  while IFS= read -r -d '' resource; do
    [ "$resource" = "$stage/skills/$name/SKILL.md" ] && continue
    awk -v mode=resource -f "$SCRIPT_DIR/claude-to-codex.awk" "$resource" > "$stage/resource.tmp"
    cp "$stage/resource.tmp" "$resource"
  done < <(find "$stage/skills/$name" -type f -name '*.md' -print0)
done
for src in "$SOURCE_DIR"/commands/*.md; do
  [ -f "$src" ] || continue
  name="$(basename "$src" .md)"
  [ ! -e "$stage/skills/$name" ] || { echo "Skill/command name collision: $name" >&2; exit 1; }
  mkdir -p "$stage/skills/$name/agents"
  awk -v mode=command -v command_name="$name" -f "$SCRIPT_DIR/claude-to-codex.awk" "$src" > "$stage/skills/$name/SKILL.md"
  printf 'policy:\n  allow_implicit_invocation: false\n' > "$stage/skills/$name/agents/openai.yaml"
done
owned_file() {
  [ -f "$1" ] && [ ! -L "$1" ] && head -n 6 "$1" | grep -qxF "$2"
}
legacy_owned() {
  if [ -L "$1" ]; then
    case "$(readlink "$1")" in *'.claude-base/'*) return 0 ;; *) return 1 ;; esac
  else
    [ -f "$1" ] && head -n 3 "$1" | grep -qxF '# generated by .claude-base/sync.sh - do not edit'
  fi
}
exclude_path() {
  local relative="$1" exclude
  $GIT_EXCLUDE || return 0
  # git supports both normal checkouts and .git files in linked worktrees.
  exclude=$(git -C "$TARGET_DIR" rev-parse --git-path info/exclude 2>/dev/null) || return 0
  case "$exclude" in /*) ;; *) exclude="$TARGET_DIR/$exclude" ;; esac
  if [ -f "$exclude" ] && grep -qxF "$relative" "$exclude"; then return 0; fi
  if $DRY_RUN; then echo "would exclude: $relative"; return; fi
  mkdir -p "$(dirname "$exclude")"
  printf '%s\n' "$relative" >> "$exclude"
}
for src in "$stage"/agents/*.toml; do
  [ -f "$src" ] || continue
  name="$(basename "$src")"
  dst="$TARGET_DIR/.codex/agents/$name"
  if [ -e "$dst" ] || [ -L "$dst" ]; then
    owned_file "$dst" '# generated by .claude-base/claude-to-codex.sh - do not edit' || { echo "preserved: $dst"; continue; }
  fi
  if $DRY_RUN; then echo "would generate: $dst"; else
    mkdir -p "$(dirname "$dst")"
    cp "$src" "$dst"
    echo "generated: $dst"
  fi
  exclude_path ".codex/agents/$name"
done
for src in "$stage"/skills/*; do
  [ -d "$src" ] || continue
  name="$(basename "$src")"
  dst="$TARGET_DIR/.agents/skills/$name"
  if [ -e "$dst" ] || [ -L "$dst" ]; then
    if [ -L "$dst" ] || ! owned_file "$dst/SKILL.md" '<!-- generated by .claude-base/claude-to-codex.sh - do not edit -->'; then
      echo "preserved: $dst"; continue
    fi
  fi
  if $DRY_RUN; then echo "would generate: $dst"; else
    mkdir -p "$(dirname "$dst")"
    [ ! -d "$dst" ] || rm -rf "$dst"
    cp -R "$src" "$dst"
    echo "generated: $dst"
  fi
  exclude_path ".agents/skills/$name"
done
# Prune generated output whose source was deleted or renamed. Ownership
# markers opt files/folders into replacement and removal; overrides opt out.
for old in "$TARGET_DIR"/.codex/agents/*.toml; do
  [ -f "$old" ] || continue
  name="$(basename "$old")"
  [ ! -e "$stage/agents/$name" ] || continue
  owned_file "$old" '# generated by .claude-base/claude-to-codex.sh - do not edit' || continue
  if $DRY_RUN; then echo "would remove stale agent: $old"; else
    rm -f "$old"
    echo "removed stale agent: $old"
  fi
done
for old in "$TARGET_DIR"/.agents/skills/*; do
  [ -d "$old" ] && [ ! -L "$old" ] || continue
  name="$(basename "$old")"
  [ ! -e "$stage/skills/$name" ] || continue
  owned_file "$old/SKILL.md" '<!-- generated by .claude-base/claude-to-codex.sh - do not edit -->' || continue
  if $DRY_RUN; then echo "would remove stale skill: $old"; else
    rm -rf "$old"
    echo "removed stale skill: $old"
  fi
done
for old in "$TARGET_DIR"/.codex/agents/*.agent.md "$TARGET_DIR"/.codex/skills/*; do
  [ -e "$old" ] || [ -L "$old" ] || continue
  legacy_owned "$old" || continue
  if $DRY_RUN; then echo "would remove legacy output: $old"; else
    rm -f "$old"
    echo "removed legacy output: $old"
  fi
done
