#!/usr/bin/env bash
set -euo pipefail
BASE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
absent_pattern() {
  if grep -Erq "$@"; then echo "FAIL: unexpected output pattern: $1" >&2; exit 1; fi
}
fixture=$(mktemp -d)
trap 'rm -rf "$fixture"' EXIT
mkdir -p "$fixture/work space/.claude-base" "$fixture/work space/repo/.codex" "$fixture/work space/repo/.git/info"
git init -q "$fixture/work space/repo"
cp -R "$BASE_DIR/agents" "$BASE_DIR/skills" "$BASE_DIR/commands" "$fixture/work space/.claude-base/"
mkdir -p "$fixture/work space/.claude-base/skills/superpower/references"
printf 'Read CLAUDE.md.\n' > "$fixture/work space/.claude-base/skills/superpower/references/guide.md"
printf '%s\n' '---' 'description: Inspect a symbol' 'allowed-tools: Read, Grep' '---' 'Inspect $ARGUMENTS.' > "$fixture/work space/.claude-base/commands/inspect.md"
cp "$BASE_DIR/sync.sh" "$fixture/work space/.claude-base/"
if [ ! -f "$BASE_DIR/lib/claude-to-codex.sh" ]; then
  echo 'FAIL: standalone shell converter is missing' >&2
  exit 1
fi
cp -R "$BASE_DIR/lib" "$fixture/work space/.claude-base/"
converter="$fixture/work space/.claude-base/lib/claude-to-codex.sh"
repo="$fixture/work space/repo"
# Helper defaults resolve through lib/ to the base repo, independent of cwd.
(cd /; bash "$converter" --dry-run) > "$fixture/default-preview"
grep -Fq "would generate: $fixture/work space/.codex/agents/researcher.toml" "$fixture/default-preview"
bash "$fixture/work space/.claude-base/lib/sync-claude.sh" --target "$fixture/direct-claude"
[ -f "$fixture/direct-claude/.claude/agents/researcher.agent.md" ]
if bash "$fixture/work space/.claude-base/sync.sh" codex </dev/null; then
  echo 'FAIL: noninteractive sync accepted implicit all' >&2; exit 1
fi
printf 'cancel\n' | bash "$fixture/work space/.claude-base/sync.sh" codex --interactive
[ ! -e "$repo/.codex/agents" ]
if bash "$fixture/work space/.claude-base/sync.sh" codex --target nonexistent; then
  echo 'FAIL: unknown target accepted' >&2; exit 1
fi
bash "$fixture/work space/.claude-base/sync.sh" codex --target repo
[ -f "$repo/.codex/agents/researcher.toml" ]
[ ! -e "$fixture/work space/.codex" ]
rm -rf "$repo/.codex/agents" "$repo/.agents"
printf '999\n2\n' | bash "$fixture/work space/.claude-base/sync.sh" codex --interactive
[ -f "$repo/.codex/agents/researcher.toml" ]
[ ! -e "$fixture/work space/.codex" ]
rm -rf "$repo/.codex/agents" "$repo/.agents"
printf '0\n' | bash "$fixture/work space/.claude-base/sync.sh" codex --interactive
[ -f "$repo/.codex/agents/researcher.toml" ]
[ -f "$fixture/work space/.codex/agents/researcher.toml" ]
rm -rf "$repo/.codex/agents" "$repo/.agents" "$fixture/work space/.codex" "$fixture/work space/.agents"
LC_ALL=C bash "$converter" --target "$fixture/locale-c"
LC_ALL=en_US.UTF-8 bash "$converter" --target "$fixture/locale-utf8"
diff -r "$fixture/locale-c" "$fixture/locale-utf8"
grep -Eq '—' "$fixture/locale-utf8/.codex/agents/docs-updater.toml"
grep -Eq '✅' "$fixture/locale-utf8/.codex/agents/task-planner.toml"
bash "$converter" --target "$repo" --dry-run
[ ! -e "$repo/.codex/agents" ]
[ ! -e "$repo/.agents" ]
bash "$converter" --target "$repo"
[ -f "$repo/.codex/agents/researcher.toml" ]
[ -f "$repo/.agents/skills/superpower/SKILL.md" ]
[ -f "$repo/.agents/skills/pr-comments/SKILL.md" ]
[ -f "$repo/.agents/skills/superpower/references/guide.md" ]
grep -Eq "description: 'Inspect a symbol'" "$repo/.agents/skills/inspect/SKILL.md"
absent_pattern 'Claude Code|CLAUDE.md|Agent tool|\$ARGUMENTS' "$repo/.agents/skills"
grep -Eq 'allow_implicit_invocation: false' "$repo/.agents/skills/pr-comments/agents/openai.yaml"
absent_pattern 'codex_model|^tools:|^model =' "$repo/.codex/agents"
absent_pattern "Claude Code|CLAUDE.md|Agent tool" "$repo/.codex/agents"
cp "$repo/.codex/agents/researcher.toml" "$fixture/first.toml"
bash "$converter" --target "$repo"
cmp "$fixture/first.toml" "$repo/.codex/agents/researcher.toml"
printf 'handwritten agent\n' > "$repo/.codex/agents/researcher.toml"
printf 'handwritten skill\n' > "$repo/.agents/skills/superpower/SKILL.md"
CODEX_MODEL_OPUS=example-model bash "$converter" --target "$repo"
test "$(cat "$repo/.codex/agents/researcher.toml")" = 'handwritten agent'
test "$(cat "$repo/.agents/skills/superpower/SKILL.md")" = 'handwritten skill'
grep -Eq '^model = "example-model"$' "$repo/.codex/agents/task-planner.toml"
printf '# generated by .claude-base/sync.sh - do not edit\n' > "$repo/.codex/agents/task-planner.agent.md"
printf 'handwritten legacy agent\n' > "$repo/.codex/agents/researcher.agent.md"
cp "$repo/.git/info/exclude" "$fixture/exclude-before"
bash "$fixture/work space/.claude-base/sync.sh" claude codex --dry-run git-exclude=true
[ -f "$repo/.codex/agents/task-planner.agent.md" ]
[ ! -e "$repo/.claude" ]
cmp "$fixture/exclude-before" "$repo/.git/info/exclude"
bash "$fixture/work space/.claude-base/sync.sh" --all codex git-exclude=true
[ ! -e "$repo/.codex/agents/task-planner.agent.md" ]
[ -f "$repo/.codex/agents/researcher.agent.md" ]
grep -Eq '^\.codex/agents/task-planner.toml$' "$repo/.git/info/exclude"
grep -Eq '^\.agents/skills/pr-comments$' "$repo/.git/info/exclude"
bash "$fixture/work space/.claude-base/sync.sh" --all claude git-exclude=false
[ -L "$repo/.claude/agents/researcher.agent.md" ]
mkdir -p "$fixture/bad/agents"
printf '%s\n' '---' 'name: invalid' 'description: |' '  unsupported multiline' '---' 'Body' > "$fixture/bad/agents/invalid.md"
if bash "$converter" --source "$fixture/bad" --target "$fixture/bad-output"; then
  echo 'FAIL: unsupported YAML was accepted' >&2; exit 1
fi
[ ! -e "$fixture/bad-output" ]
mkdir -p "$fixture/collision/agents"
cp "$BASE_DIR/agents/researcher.agent.md" "$fixture/collision/agents/same.md"
cp "$BASE_DIR/agents/task-planner.agent.md" "$fixture/collision/agents/same.agent.md"
if bash "$converter" --source "$fixture/collision" --target "$fixture/collision-output"; then
  echo 'FAIL: colliding agent filenames were accepted' >&2; exit 1
fi
[ ! -e "$fixture/collision-output" ]
workspace="$fixture/work space"
mkdir -p "$workspace/plain/.codex" "$workspace/unselected"
git init -q "$workspace/new-repo"
bash "$workspace/.claude-base/sync.sh" codex --dry-run
[ ! -e "$workspace/new-repo/.codex" ]
[ ! -e "$workspace/new-repo/.agents" ]
bash "$workspace/.claude-base/sync.sh" --all codex
[ -f "$workspace/new-repo/.codex/agents/task-planner.toml" ]
[ -f "$workspace/new-repo/.agents/skills/pr-comments/SKILL.md" ]
[ ! -e "$workspace/new-repo/.claude" ]
[ ! -e "$workspace/.claude-base/.codex" ]
[ -f "$workspace/plain/.codex/agents/task-planner.toml" ]
[ -f "$workspace/plain/.agents/skills/pr-comments/SKILL.md" ]
[ ! -e "$workspace/plain/.git" ]
[ ! -e "$workspace/plain/.claude" ]
[ ! -e "$workspace/unselected/.codex" ]
[ -f "$workspace/.codex/agents/task-planner.toml" ]
# Delete an agent and command, and rename a skill. Overrides and unrelated
# links survive; both the workspace and child project outputs must converge.
printf 'handwritten extra\n' > "$repo/.codex/agents/custom.toml"
ln -s "$fixture/unrelated-missing-source" "$repo/.claude/agents/custom.md"
mv "$workspace/.claude-base/skills/agent-mode-instructions" "$workspace/.claude-base/skills/renamed"
sed 's/name: agent-mode-instructions/name: renamed/' "$workspace/.claude-base/skills/renamed/SKILL.md" > "$fixture/renamed.md"
cp "$fixture/renamed.md" "$workspace/.claude-base/skills/renamed/SKILL.md"
rm "$workspace/.claude-base/agents/task-planner.agent.md" "$workspace/.claude-base/agents/researcher.agent.md" "$workspace/.claude-base/commands/pr-comments.md"
rm -rf "$workspace/.claude-base/skills/superpower"
bash "$workspace/.claude-base/sync.sh" claude codex --dry-run
[ -f "$repo/.codex/agents/task-planner.toml" ]
[ -L "$repo/.claude/agents/task-planner.agent.md" ]
[ -f "$repo/.agents/skills/pr-comments/SKILL.md" ]
bash "$workspace/.claude-base/sync.sh" --all claude codex
for target in "$repo" "$workspace/plain" "$workspace"; do
  [ ! -e "$target/.codex/agents/task-planner.toml" ]
  [ ! -e "$target/.agents/skills/pr-comments" ]
  [ ! -e "$target/.agents/skills/agent-mode-instructions" ]
  [ -f "$target/.agents/skills/renamed/SKILL.md" ]
done
[ ! -L "$repo/.claude/agents/task-planner.agent.md" ]
[ ! -L "$repo/.claude/commands/pr-comments.md" ]
[ ! -L "$repo/.claude/skills/agent-mode-instructions" ]
[ -L "$repo/.claude/skills/renamed" ]
[ -L "$repo/.claude/agents/custom.md" ]
test "$(cat "$repo/.codex/agents/custom.toml")" = 'handwritten extra'
test "$(cat "$repo/.codex/agents/researcher.toml")" = 'handwritten agent'
test "$(cat "$repo/.agents/skills/superpower/SKILL.md")" = 'handwritten skill'
[ ! -e "$workspace/plain/.codex/agents/researcher.toml" ]
[ ! -e "$workspace/plain/.agents/skills/superpower" ]
echo 'PASS: conversion, UTF-8, dry run, reruns, overrides, migration, non-Git targets, deletion/rename cleanup, malformed input'
